### ISSUE TITLE
SEGMENT_SEPARATOR

### ISSUE THREAD

**Issue by premedios** [wesbos/Cobalt2-iterm#1]
After installing the cobalt2 zsh theme, my segment separator is not seamless...it's just a black block with a white square.

**Comment by dankraus** [comment]
I was having the same issue. Installed powerline fonts, set the fonts accordingly. I used @jcypret 's fork and worked perfectly. Thanks!

**Comment by samuelbran** [comment]
Same issue, @jcypret fork worked perfectly

**Comment by wesbos** [comment]
@jcypret Ah - sorry I didn't see this earlier. Can you submit a PR?

**Comment by jcypret** [comment]
No problem. I have created the pull request #3

**Comment by jandetlefsen** [comment]
still broken for me after following all the steps here, OSX 10.10.3

**Comment by samuelbran** [comment]
@jandetlefsen did you changed both Regular font and Non-ASCII font options for a Powerline font?

**Comment by jandetlefsen** [comment]
oh that did the trick, thanks

**Comment by jandetlefsen** [comment]
thanks for putting this together, looks fantastic now!

**Comment by samuelbran** [comment]
Hell yeah! thanks @wesbos

**Comment by nrutter2000** [comment]
I was having a little problem with this until I found this issue. Maybe add a little note to the readme about changing the font for each type to 'Inconsolata for Powerline' once the powerline fonts have been installed... Happy to do it if need be.

**Comment by matplane** [comment]
+1 to @nrutter2000 comment ;)

**Comment by wesbos** [comment]
@nrutter2000 Yeah that would be great!

**Comment by nrutter2000** [comment]
No worries. I've created pull request #4
