### ISSUE TITLE
Unicode problem

### ISSUE THREAD

**Issue by joshzandman** [wesbos/Cobalt2-iterm#13]
Hi Wes,

I've been troubleshooting this for awhile with no luck. Would love your help!

<img width="980" alt="screen shot 2015-11-27 at 1 02 22 pm" src="https://cloud.githubusercontent.com/assets/5635133/11446602/4c5901ee-9507-11e5-97ad-14474ace7483.png">

That's what appears. I have Inconsolata-g for Powerline (updated patch)

Thanks

**Comment by wesbos** [comment]
did you set the font for iTerm to be that font?

**Comment by joshzandman** [comment]
I did, yes - in both font option areas as well.

On Fri, Nov 27, 2015 at 2:56 PM Wes Bos <notifications@github.com> wrote:

> did you set the font for iTerm to be that font?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wesbos/Cobalt2-iterm/issues/13#issuecomment-160196330>
> .
>
-- 
Josh Zandman
808-646-0477
zandman.com

**Comment by wesbos** [comment]
Where did you get the patched powerline font from? 

A bunch of people have had this issue and it seems like its an issue with either the wrong font being installed, or the font not being applied. 

Can you post your settings? It should look like this:

![image](https://cloud.githubusercontent.com/assets/176013/11447642/6f0f719a-9517-11e5-85b9-875214f642af.png)

**Comment by joshzandman** [comment]
Hi Wes,

I went searching for that exact font name and found it here:
https://github.com/powerline/fonts/blob/master/Inconsolata/Inconsolata%20for%20Powerline.otf
<https://mailtrack.io/trace/link/61c77d5e21d2aa3eb6cb6836e03626fe2aee48dc?url=https%3A%2F%2Fgithub.com%2Fpowerline%2Ffonts%2Fblob%2Fmaster%2FInconsolata%2FInconsolata%2520for%2520Powerline.otf&signature=6f8ab9bb2bc31020>

Now it works perfectly!

Thanks for your help!




Josh Zandman
Git
<https://mailtrack.io/trace/link/631cf3e030495b48446139bd80ed6ff9dc6c5799?url=https%3A%2F%2Fgithub.com%2Fjoshzandman&signature=50d14ba4b9dde22a>
 | in
<https://mailtrack.io/trace/link/83290a2619147fa39e27a3a5a042548c56facb62?url=https%3A%2F%2Fwww.linkedin.com%2Fin%2Fjoshzandman&signature=348c4083989c9509>
808 646 0477
