### ISSUE TITLE
getting gear icon at start of prompt

### ISSUE THREAD

**Issue by johnantoni** [wesbos/Cobalt2-iterm#14]
installed powerline font inconsolata & iterm2 theme but getting gear icon at the start of the prompt?

any ideas?

using iterm2, build 2.9

<img width="198" alt="screen shot 2016-02-19 at 1 29 10 pm" src="https://cloud.githubusercontent.com/assets/15571/13184995/f7866cd6-d70c-11e5-946f-2af74dc7971a.png">

**Comment by wesbos** [comment]
That is bizarre. 

Do you see it in regular terminaltoo? Or just iTerm?

**Comment by johnantoni** [comment]
Tried in normal Terminal and also appearing, think it might be coming off the Inconsolata font.

**Comment by wesbos** [comment]
Oh, you are probably running a job in the background. 

https://github.com/wesbos/Cobalt2-iterm/blob/master/cobalt2.zsh-theme#L109

I've never had this before, but its a feature that came from the theme I forked.

**Comment by johnantoni** [comment]
found it, had an alias for 'jobs'.

will close this, thanks Wes.
