### ISSUE TITLE
Trim long paths in prompt

### ISSUE THREAD

**Issue by wesbos** [wesbos/Cobalt2-iterm#15]
Sometimes the terminal prompt gets too long:

![](http://wes.io/gHRd/content)

I'd like to trim the leftmost parts of the path and replace it with an ellipsis `…`

Here is what I'm thinking. ZSH has an env variable called `$COLUMNS` which tells you how many chars wide the current terminal is. 

What if we make sure that there is always enough for 50 (or better yet, have that number set via an env variable) characters in the prompt? It would look like:

`…-long-dir-name/images/icons`

Anyone want to give this a shot?

**Comment by wesbos** [comment]
Looks like this might be easier than I thought : http://stackoverflow.com/questions/30323993/zsh-shorten-length-of-current-path/30507499#30507499

```bash
To specify a number of shown trailing components of the path insert an integer into corresponding escape sequence in your prompt. In your case, %2~ will do the trick. Excerpt from zshmisc(1):

%d 
%/     Current working directory.  If an integer follows the `%', 
       it specifies a number of trailing components of the current 
       working directory to show; zero means the whole path.  A 
       negative integer specifies leading  components, i.e. %-1d 
       specifies the first component.

%~     As  %d  and  %/, but if the current working directory starts
       with $HOME, that part is replaced by a `~'. Furthermore, if 
       it has a named directory as its prefix, that part is replaced 
       by a `~' followed by the name of the directory, but only if 
       the result is shorter than the full path; see Dynamic and 
       Static named directories in zshexpn(1).
```

**Comment by JonBellah** [comment]
So in my Agnoster theme, I'm using

```
# Dir: current working directory
prompt_dir() {
  prompt_segment blue black '%2~'
}
```

Which trims it to the last two directories.

**Comment by wesbos** [comment]
I think I still prefer character count because the directory length could be all over the place.

**Comment by wesbos** [comment]
Going to try it with the last 3 dirs for a few days and see if I like it 

![](http://wes.io/gHZY/content)

**Comment by deecewan** [comment]
eh. that's a pretty good solution, actually.

**Comment by mcornella** [comment]
You could also use [string truncation prompt sequences](http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html#Conditional-Substrings-in-Prompts). For instance: `%15<...<%~%<<` would truncate paths longer than 15 characters and replace the truncated part with `...`. 

You can combine that with arithmetic expressions: `$(( $COLUMNS - 50 ))` where 50 is the desired amount of space left. You would have to account for the length of the replacer string and the rest of prompt characters you have (git prompt, other symbols, etc.).

All combined, it would be something like this:
```zsh
prompt_dir() {
    prompt_segment blue black "%$(( $COLUMNS - 53 ))<...<%~%<<"
}
```

You can test that sequence before settling for the appropriate length with `print -P`:
```
$ pwd
/home/user/code/Dropbox/workshops/es6-workshop/examples and exercises
$ print -P "%$(( $COLUMNS - 53 ))<...<%~%<<"
.../es6-workshop/examples and exercises
```

**Comment by vitormalencar** [comment]
this combination is  awesome @mcornella 

```{r, engine='shell', count_lines}
prompt_dir() {
  prompt_segment blue black "%$(( $COLUMNS - 61 ))<...<%3~%<<"
}

```

works really nice so far 

![captura de tela 2016-06-09 as 13 48 58](https://cloud.githubusercontent.com/assets/7741167/15938343/2a125ec4-2e49-11e6-80b1-edcd4ad1e35f.png)
![captura de tela 2016-06-09 as 13 49 17](https://cloud.githubusercontent.com/assets/7741167/15938344/2a14edc4-2e49-11e6-9478-546418dd91c0.png)
![captura de tela 2016-06-09 as 13 50 21](https://cloud.githubusercontent.com/assets/7741167/15938346/2a17569a-2e49-11e6-961e-470ac6190aa5.png)

**Comment by mcornella** [comment]
That's awesome, glad to help!

**Comment by AnimiVulpis** [comment]
I think you can omit the `$(( $COLUMNS - 61))` entirely.
Try to use the a negative number like this `%-42<...<`
>this numeric argument may be negative, in which case the truncation length is determined by subtracting the absolute value of the numeric argument from the number of character positions remaining on the current prompt line. If this results in a zero or negative length, a length of 1 is used. **In other words, a negative argument arranges that after truncation at least n characters remain before the right margin (left margin for RPROMPT)**

[zsh-docs about prompt-expansion](http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html#Conditional-Substrings-in-Prompts)

**Comment by mcornella** [comment]
That is an awesome find @AnimiVulpis! The updated prompt_dir function should look like this, then:
```zsh
prompt_dir() {
    prompt_segment blue black "%-53<...<%~%<<"
}
```

**Comment by mcornella** [comment]
An Oh My Zsh user implemented a Fish-like path prompt as a plugin: https://github.com/robbyrussell/oh-my-zsh/pull/5262 (enable `shrink-path` plugin).

**Comment by AnimiVulpis** [comment]
Thank you very much for this information.

I already like the tab-safe mode and will take a close look at this code (to understand it) to adapt it to my needs.
Like adding the possibility to truncate the string if it gets to long.

_Maybe even creating my first zsh plugin_

**Comment by egormasalitin** [comment]
@mcornella @AnimiVulpis 
Thank you guys, it is really awesome, it saved my 2017 :muscle:

**Comment by wesbos** [comment]
this has been fixed! https://github.com/wesbos/Cobalt2-iterm/commit/bdacb8d52ce1cd3cd991299a71c93aa0f458397f

**Comment by madsonic** [comment]
this is awesome! it should be made into a gist so that it can be bookmarked/saved

**Comment by AnimiVulpis** [comment]
I never created a plugin from this.
But this path truncation is part of my zsh-theme.

You can see it [here](https://github.com/AnimiVulpis/dotfiles/blob/master/zsh/animivulpis.zsh-theme#L40).

When you search for `_width` you will see all the different places where I use the same approach.

Feel free to ask away

**Comment by AnimiVulpis** [comment]
@erichodges not really related to this topic but take a look [here](https://github.com/wesbos/Cobalt2-iterm/blob/master/cobalt2.zsh-theme#L52)
Copy/Clone/Modify the theme and change this symbol, it should do the trick.

_(And don't hesitate to open a new ticket in the future IMHO)_

**Comment by erichodges** [comment]
@AnimiVulpis Yeah, sorry about putting the question in the wrong place :-). Thanks for getting back to me!
