### ISSUE TITLE
Small Icons don't show up

### ISSUE THREAD

**Issue by daqo** [wesbos/Cobalt2-iterm#16]
Any Idea why this is happening? Thanks!

![image](https://cloud.githubusercontent.com/assets/1572895/18963114/7337e39e-8628-11e6-91a8-684731fb5e1d.png)

**Comment by wesbos** [comment]
Hey! You need the patched powerline font. 

Check step 5: https://github.com/wesbos/Cobalt2-iterm#step-by-step-installation

Then make sure you set your settings to this:


![](http://wes.io/hc9X/content)

**Comment by daqo** [comment]
Woot! Thank you.

**Comment by thundernixon** [comment]
Just to add some extra info in case anyone else runs into the same variation of this issue that I did...

If you're using a Hotkey Window, you may need to update the fonts and colors in there, as well:

![image](https://user-images.githubusercontent.com/7355414/34297649-acb265ec-e719-11e7-8b4e-3cc1068ba504.png)
