### ISSUE TITLE
text color for certain output statements too dark

### ISSUE THREAD

**Issue by TheRealAlan** [wesbos/Cobalt2-iterm#2]
This seems to be a pretty common issue with iTerm themes as I tried some others before posting, but I've noticed this happen in certain cases where some output text is black on the already dark background. I'm not sure what the specific output type is, I'm not sure how to go about changing it. I just thought I would post it and see if you might know more.

![screen shot 2014-12-22 at 10 02 14 am](https://cloud.githubusercontent.com/assets/1688910/5526471/cf2219aa-89c1-11e4-9b8f-a1d5eda18f65.png)

**Comment by wesbos** [comment]
1.5 years later I'm just seeing this :sob: 

Hrm not sure how to solve this - it's more an issue with the thing that outputs the text.
