### ISSUE TITLE
Remove "" from ZSH_THEME=“cobalt2”

### ISSUE THREAD

**Issue by sebaslm** [wesbos/Cobalt2-iterm#28]
Don't know why this happened, but I got this error when changing the name of the theme to Colbalt2

`~/.oh-my-zsh/oh-my-zsh.sh:source:110: no such file or directory: ~/.oh-my-zsh/themes/“cobalt2”.zsh-theme`

I fixed it by deleting the quotation marks around the theme name, like so:

`ZSH_THEME=cobalt2`

Then it worked perfect!

**Comment by abyabrkal** [comment]
This is right. I had the same issue.
Double quotes needs to be removed, while entering theme name.

**Comment by wesbos** [comment]
thanks! fixed this
