### ISSUE TITLE
black background

### ISSUE THREAD

**Issue by Helfull** [wesbos/Cobalt2-iterm#31]
hey,

the `black` background seems not to work properly

![image](https://user-images.githubusercontent.com/720645/36340754-4a892756-13e3-11e8-87b1-17aa4d3a8128.png)

i am running this on hyper.is with zsh on bash on windows.

using another color does work except `lightBlack`

**Comment by wesbos** [comment]
Hey - i'd open an issue with WSL on this

**Comment by PhilippSchweizer** [comment]
Hi @Helfull. Did you had any luck with fixing this? I searched the WSL repo for issues on it but couldn't find any of relevance.
