### ISSUE TITLE
Error installing cobalt2 theme

### ISSUE THREAD

**Issue by brunogenaro** [wesbos/Cobalt2-iterm#5]
I'm getting this error after install the theme and changed the ZSH_THEME to "cobalt2":

oh-my-zsh/themes/cobalt2.zsh-theme:5: parse error near `\n'
brunogenaro@

Any idea?

**Comment by zkingdesign** [comment]
I'm getting the same issue. Please help.

**Comment by pixelbandito** [comment]
Yup, same issue.

**Comment by wesbos** [comment]
Hrm - try download it again?  There are no `\n` in the theme so it makes me think the download is corrupt. 

Try download the entire repo and unzip it from there

**Comment by pixelbandito** [comment]
I had the same thought, but I just downloaded the file and moved it straight to the destination with a terminal command - I can't see any reason it should have changed.



—
Pardon my thumbly typing

**Comment by jdgomeza** [comment]
I had the same problem. I was not using the correct link to download the file.

If you want to only download the theme file use the RAW content link

https://raw.githubusercontent.com/wesbos/Cobalt2-iterm/master/cobalt2.zsh-theme

```
$wget https://raw.githubusercontent.com/wesbos/Cobalt2-iterm/master/cobalt2.zsh-theme
```

Or as @wesbos indicates, you can clone the repository or download the zip file.

**Comment by wesbos** [comment]
Thank you :)

**Comment by itmanagerkz** [comment]
> I had the same problem. I was not using the correct link to download the file.
> 
> If you want to only download the theme file use the RAW content link
> 
> https://raw.githubusercontent.com/wesbos/Cobalt2-iterm/master/cobalt2.zsh-theme
> 
> ```
> $wget https://raw.githubusercontent.com/wesbos/Cobalt2-iterm/master/cobalt2.zsh-theme
> ```
> 
> Or as @wesbos indicates, you can clone the repository or download the zip file.

Still have this issue in 2020.
Thank you!
